import { MetroLine } from '@/types/metro';
import { Interchange } from '@/types/station';
import { stationData } from './station-data';

export const metroLines: MetroLine[] = [
  {
    id: 'red',
    name: 'Red Line',
    stations: [
      stationData.secretariat,
      stationData.paradeGround,
      stationData.shaheedEMillat,
      stationData.seventhAvenue,
      stationData.stockExchange,
      stationData.pims,
      stationData.kachehry,
      stationData.ibnESina,
      stationData.chaman,
      stationData.kashmirHighway,
      stationData.faizAhmadFaiz,
      stationData.khayabanEJohar,
      stationData.potohar,
      stationData.ijPrincipal,
      stationData.faizabad,
      stationData.shamsabad,
      stationData.sixthRoad,
      stationData.rehmanabad,
      stationData.chandaniChowk,
      stationData.warisKhan,
      stationData.committeeChowk,
      stationData.liaquatBagh,
      stationData.marrirChowk,
      stationData.saddar,
    ],
  },
  {
    id: 'orange',
    name: 'Orange Line',
    stations: [
      stationData.faizAhmadFaiz,
      stationData.g10,
      stationData.nha,
      stationData.policeFoundation,
      stationData.nust,
      stationData.g13,
      stationData.golraMorr,
      stationData.n5,
      stationData.airport,
    ],
  },
  {
    id: 'green',
    name: 'Green Line',
    stations: [
      stationData.pims_gate,
      stationData.pims_children_hospital,
      stationData.g7g8,
      stationData.cda,
      stationData.aabpara,
      stationData.foreignOffice,
      stationData.lakeviewPark,
      stationData.malpur,
      stationData.shahdara,
      stationData.bharakau,
    ],
  },
  {
    id: 'blue',
    name: 'Blue Line',
    stations: [
      stationData.pims_gate,
      stationData.pims_children_hospital,
      stationData.g7g8,
      stationData.h8Shakarparia,
      stationData.i8ParadeGround,
      stationData.sohan,
      stationData.dhokeKalaKhan,
      stationData.iqbalTown,
      stationData.kuriRoad,
      stationData.ziaMasjid,
      stationData.khannaPul,
      stationData.fazaia,
      stationData.gangal,
      stationData.koralChowk,
      stationData.gulberg,
    ],
  },
  {
    id: 'fr_1',
    name: 'FR-1',
    stations: [
      stationData.sohan,
      stationData.faizabad,
      stationData.ijPrincipal,
      stationData.potohar,
      stationData.mciModelSchool,
      stationData.cdaComplaintCenter,
      stationData.ogtiStop,
      stationData.suiGasStop,
      stationData.ptclI10,
      stationData.iescoI10Markaz,
      stationData.korangRoad,
      stationData.shamaPark,
      stationData.metroCashAndCarry,
    ],
  },
  {
    id: 'fr_3a',
    name: 'FR-3A',
    stations: [
      stationData.pims_gate,
      stationData.pims,
      stationData.f8Katchery,
      stationData.f8Markaz,
      stationData.raviGateF9,
      stationData.shaheenChowk,
      stationData.bahriaUniversity,
      stationData.navalComplex,
      stationData.faisalMasjid,
    ],
  },
  {
    id: 'fr_4',
    name: 'FR-4',
    stations: [
      stationData.pims_gate,
      stationData.pims_children_hospital,
      stationData.rescue15,
      stationData.bankColony,
      stationData.salaiCentre,
      stationData.sitaraMarket,
      stationData.pullyStop,
      stationData.iqbalHall,
      stationData.g61,
      stationData.melodyMarket,
      stationData.abparaMarket,
      stationData.youthHostel,
      stationData.metropolitanCorporation,
      stationData.icbCollege,
      stationData.nadraChowk,
      stationData.lodgesPark,
      stationData.sukhChaynPark,
      stationData.ministryOfForeignAffairs,
      stationData.radioPakistan,
      stationData.nationalLibrary,
      stationData.secretariatePoliceStation,
      stationData.diplomaticEnclaveGate4,
      stationData.aiwanESadarColony,
      stationData.muslimColony,
      stationData.bariImam,
    ],
  },
  {
    id: 'fr_4a',
    name: 'FR-4A',
    stations: [
      stationData.bariImam,
      stationData.muhallahNooriBagh,
      stationData.communityHealthCentre,
      stationData.dTypeQuaidEAzamColony,
      stationData.cTypeQuaidEAzamColony,
      stationData.babulQuaid,
      stationData.qau,
    ],
  },
  {
    id: 'fr_7',
    name: 'FR-7',
    stations: [
      stationData.pims_gate,
      stationData.pims_children_hospital,
      stationData.noriHospital,
      stationData.dentalHospital,
      stationData.g8Markaz,
      stationData.developmentPark,
      stationData.chaman,
      stationData.g9_4_Park,
      stationData.karachiCompany,
      stationData.g9Markaz,
      stationData.policeFlats,
      stationData.collegeMorh,
      stationData.g10Markaz,
      stationData.phaFlats,
      stationData.tankiStop,
      stationData.greenbeltG10G11,
      stationData.instituteOfModernStudies,
      stationData.g11Markaz,
      stationData.mehrabad,
      stationData.nust,
    ],
  },
  {
    id: 'fr_8a',
    name: 'FR-8A',
    stations: [
      stationData.pims_gate,
      stationData.zeroPakMonument,
      stationData.cda,
      stationData.aabpara,
      stationData.foreignOffice,
      stationData.kashmirChowk,
      stationData.rawalChowk,
      stationData.rawalTown,
      stationData.schoolBoardStop,
      stationData.rawalDamColony,
      stationData.narcColony,
      stationData.nihAllergyCenter,
      stationData.shahzadTown,
      stationData.parkViewKuriRoad,
      stationData.greenAvenue,
      stationData.chattaBakhtawar,
      stationData.hostelCity,
      stationData.comsatsUniversity,
      stationData.tammaStop,
      stationData.tramriChowk,
    ],
  },
  {
    id: 'fr_8c',
    name: 'FR-8C',
    stations: [
      stationData.pims_gate,
      stationData.ttStop,
      stationData.h8Shakarparia,
      stationData.i8ParadeGround,
      stationData.faizabadInterchange,
      stationData.itpCentre,
      stationData.margallaTown,
      stationData.gardenAvenue,
      stationData.rawalChowk,
      stationData.rawalTown,
      stationData.schoolBoardStop,
      stationData.rawalDamColony,
      stationData.narcColony,
      stationData.nihAllergyCenter,
      stationData.shahzadTown,
      stationData.parkViewKuriRoad,
      stationData.greenAvenue,
      stationData.chattaBakhtawar,
      stationData.hostelCity,
      stationData.comsatsUniversity,
      stationData.tammaStop,
      stationData.tramriChowk,
    ],
  },
  {
    id: 'fr_9',
    name: 'FR-9',
    stations: [
      stationData.khannaPul,
      stationData.ziaMasjid,
      stationData.kuriRoad,
      stationData.iqbalTown,
      stationData.dhokeKalaKhan,
      stationData.sohan,
      stationData.faizabad,
      stationData.ijPrincipal,
      stationData.pindoraChungi,
      stationData.katarianChungi,
      stationData.katarianPull,
      stationData.cdaStop,
      stationData.pullyStop,
      stationData.mandiMorh,
      stationData.faujiColony,
      stationData.carriageFactory,
      stationData.westridge,
      stationData.ctti,
      stationData.socialSecurityHospital,
      stationData.britishHomes,
      stationData.pirWadhaiMorh,
      stationData.kohinoorMillColony,
      stationData.kohinoorMill,
      stationData.golraMorhChowk,
      stationData.golraMorr,
    ],
  },
  {
    id: 'fr_14',
    name: 'FR-14',
    stations: [
      stationData.bharakau,
      stationData.shahdara,
      stationData.malpur,
      stationData.lakeviewPark,
      stationData.kashmirChowk,
      stationData.rawalChowk,
      stationData.gardenAvenue,
      stationData.margallaTown,
      stationData.itpCentre,
      stationData.sohan,
      stationData.faizabad,
      stationData.ijPrincipal,
      stationData.pindoraChungi,
      stationData.katarianChungi,
      stationData.katarianPull,
      stationData.cda,
      stationData.pullyStop,
      stationData.mandiMorh,
    ],
  },
  {
    id: 'fr_14a',
    name: 'FR-14A',
    stations: [
      stationData.bharakau,
      stationData.colAmmanullahRoad,
      stationData.athalChowk,
      stationData.bharakauBazar,
      stationData.jhugi,
      stationData.bheraPul,
      stationData.imtiazMart,
      stationData.akbarNiazi,
      stationData.phulgran,
      stationData.dhokBadam,
      stationData.punjabCollege,
      stationData.alwadiColony,
      stationData.satraMeel,
    ],
  },
  {
    id: 'fr_15',
    name: 'FR-15',
    stations: [
      stationData.khannaPul,
      stationData.fazaia,
      stationData.gangal,
      stationData.koralChowk,
      stationData.gulberg,
      stationData.tuthStop,
      stationData.pwdHousingSociety,
      stationData.sohanGardenEBlock,
      stationData.sohanGardenGBlock,
      stationData.sohanGardenHBlock,
      stationData.riverGarden,
      stationData.kaakPul,
      stationData.dhaGate8,
      stationData.dhaGate7,
      stationData.suparco,
      stationData.tChowk,
    ],
  },
];

/**
 * Walking shortcuts between stations for transfers
 * This defines stations where users can reasonably walk between to transfer lines
 * instead of taking transit connections
 */
export const walkingShortcuts: Array<{
  from: string;
  to: string;
  priority: number; // Higher number means higher priority (0-10, 10 being highest)
}> = [
  {
    from: 'sohan',
    to: 'faizabad',
    priority: 7, // High priority
  },
  {
    from: 'faizabadInterchange',
    to: 'faizabad',
    priority: 10, // High priority
  },
  {
    from: 'pims',
    to: 'pims_gate',
    priority: 8,
  },
];

/**
 * Major interchange stations in the network
 * These are stations where multiple lines meet, enabling transfers
 */
export const MAJOR_INTERCHANGES: Interchange[] = [
  {
    stationId: 'faizAhmadFaiz',
    lines: ['red', 'orange'],
    transferImportance: 10, // Higher means more important
  },
  {
    stationId: 'pims_gate',
    lines: ['green', 'blue'],
    transferImportance: 8,
  },
  {
    stationId: 'faizabad',
    lines: ['red', 'fr_1', 'fr_9', 'fr_14'],
    transferImportance: 7,
  },
  {
    stationId: 'sohan',
    lines: ['blue', 'fr_1', 'fr_9', 'fr_14'],
    transferImportance: 6,
  },
];
